=== GeeXboX/geexbox.github.io/xml/geexbox.dtd
<!ELEMENT article (define | section)*>
<!ELEMENT define (#PCDATA | use | center | page | webmaster | users | devel | xhtml | css | openweb)*>
<!ELEMENT use EMPTY>
<!ELEMENT section (content | subsection)*>
<!ELEMENT subsection (content)*>
<!ELEMENT content (#PCDATA | use | center | page | webmaster | users | devel | xhtml | css | openweb)*>
<!ELEMENT center (#PCDATA | use | center | page | webmaster | users | devel | xhtml | css | openweb)*>
<!ELEMENT page EMPTY>
<!ELEMENT webmaster EMPTY>
<!ELEMENT users EMPTY>
<!ELEMENT devel EMPTY>
<!ELEMENT xhml EMPTY>
<!ELEMENT css EMPTY>
<!ELEMENT openweb EMPTY>

<!ATTLIST define name NMTOKEN #REQUIRED>
<!ATTLIST use name NMTOKEN #REQUIRED>
<!ATTLIST content lang NMTOKEN "en"
                  title CDATA #IMPLIED>
<!ATTLIST page name NMTOKEN #REQUIRED>
<!ATTLIST xhml title CDATA #IMPLIED>
<!ATTLIST css title CDATA #IMPLIED>
<!ATTLIST openweb title CDATA #IMPLIED>


<!ELEMENT text (#PCDATA)>
<!ATTLIST text lang NMTOKEN "en">


<!ELEMENT banner (logo, langs)>
<!ELEMENT logo EMPTY>
<!ELEMENT langs (text*)>

<!ATTLIST logo link  CDATA #REQUIRED
               src   CDATA #REQUIRED
               alt   CDATA #REQUIRED
               title CDATA #REQUIRED>


<!ELEMENT menu (item*)>
<!ELEMENT item (text*, subitem*)>
<!ELEMENT subitem (text*)>

<!ATTLIST item name NMTOKEN #REQUIRED
               id   NMTOKEN #REQUIRED>
<!ATTLIST subitem name NMTOKEN #REQUIRED
                  url  CDATA   #REQUIRED>


<!ELEMENT ours (content)*>

=== GeeXboX/geexbox.github.io/xml/menu.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE menu SYSTEM "geexbox.dtd">

<menu>
  <item name="geexbox" id="geexbox">
    <text lang="en">GeeXboX</text>
    <text lang="fr">GeeXboX</text>

    <subitem name="get_started" url="start.html">
      <text lang="en">Get Started ...</text>
      <text lang="fr">Par où commencer ...</text>
    </subitem>

    <subitem name="screenshots" url="screenshot.html">
      <text lang="en">Screenshots</text>
      <text lang="fr">Captures d'écrans</text>
    </subitem>

    <subitem name="bugs" url="bugs.html">
      <text lang="en">Bugs / TODO</text>
      <text lang="fr">Bugs / Correctifs</text>
    </subitem>
  </item>

  <item name="ressources" id="ressources">
    <text lang="en">Ressources</text>
    <text lang="fr">Ressources</text>

    <subitem name="require" url="requirements.html">
      <text lang="en">Requirements</text>
      <text lang="fr">Pré-requis</text>
    </subitem>

    <subitem name="download" url="downloads.html">
      <text lang="en">Downloads</text>
      <text lang="fr">Téléchargements</text>
    </subitem>

    <subitem name="doc" url="doc.html">
      <text lang="en">Documentation</text>
      <text lang="fr">Documentation</text>
    </subitem>
  </item>

  <item name="feedback" id="feedback">
    <text lang="en">FeedBack</text>
    <text lang="fr">En Savoir Plus</text>

    <subitem name="faq" url="faq.html">
      <text lang="en">FAQ</text>
      <text lang="fr">FAQ</text>
    </subitem>

    <subitem name="links" url="links.html">
      <text lang="en">Links</text>
      <text lang="fr">Liens</text>
    </subitem>

    <subitem name="press" url="press.html">
      <text lang="en">Press</text>
      <text lang="fr">Presse</text>
    </subitem>

    <subitem name="contact" url="contact.html">
      <text lang="en">Contact</text>
      <text lang="fr">Contact</text>
    </subitem>

    <subitem name="forum" url="../forum/">
      <text lang="en">Forum</text>
      <text lang="fr">Forum</text>
    </subitem>
  </item>
</menu>
